config/routes.rb
Rails.application.routes.draw do
  root 'snippets#index'
  resources :snippets do
    post :clone
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  resources  :users, only: [] do
    resources :snippets, only: :index
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, Snippet, user_id: user.id
    can :read, Snippet, privacy_setting: Snippet.privacy_settings[:_public]
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user

  enum privacy_setting: [:_public, :_private]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :snippets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include CanCan::ControllerAdditions
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_snippet, only: [:show, :edit, :update, :destroy, :clone]
  before_action :can_manage?, only: [:edit, :update, :destroy]
  before_action :can_read?, only: [:show, :clone]
  respond_to :html

  def index
    user = User.find_by_id(params[:user_id]) if params[:user_id]
    @snippets = Snippet.includes(:user)
    @snippets = @snippets.where(user: user) if user
    respond_with(@snippets)
  end

  def show
    respond_with(@snippet)
  end

  def new
    @snippet = Snippet.new
    respond_with(@snippet)
  end

  def edit
  end

  def create
    @snippet = current_user.snippets.new(snippet_params)
    @snippet.save
    respond_with(@snippet)
  end

  def update
    @snippet.update(snippet_params)
    respond_with(@snippet)
  end

  def destroy
    @snippet.destroy
    respond_with(@snippet)
  end

  def clone
    new_snippet = @snippet.dup
    new_snippet.user = current_user
    new_snippet.save!
    flash[:notice] = "Snippet cloned"
    redirect_to new_snippet
  end

  private
    def set_snippet
      @snippet = Snippet.find(params[:id] || params[:snippet_id])
    end

    def can_manage?
      no_permition unless can? :manage, @snippet
    end

    def can_read?
      no_permition unless can? :read, @snippet
    end

    def no_permition
      flash[:notice] = "No permition"
      redirect_to root_path
    end

    def snippet_params
      params.require(:snippet).permit(:title, :code, :syntax, :privacy_setting)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Csm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/default.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/highlight.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          CSM
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to('New Snippet', new_snippet_path) %>
          </li>
          <li>
            <%= link_to('My Snippets', user_snippets_path(current_user)) %>
          </li>
          <li>
         		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
         	</li>
        <% else %>
         	<li>
         		<%= link_to('Login', new_user_session_path)  %>
         	</li>
         <% end %>
      </ul>
      </div>
    </div>
  </nav>
  <%#= flash_messages %>
  <div class="col-md-offset-2 col-md-8">
    <% flash.each do |key, value| %>
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <div class="flash <%= key %> alert alert-info alert-dismissable"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet, :html => { :class => "form-horizontal snippet" } do |f| %>

  <% if @snippet.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @snippet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:code) %>
  </div>
  <div class="form-group">
    <%= f.label :syntax, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :syntax, :class => 'form-control' %>
    </div>
    <%=f.error_span(:syntax) %>
  </div>
  <div class="form-group">
    <%= f.label :privacy_setting, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :privacy_setting, Snippet.privacy_settings.keys.map{ |ps| [ps.titleize, ps] }, :class => 'form-control' %>
    </div>
    <%=f.error_span(:privacy_setting) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                snippets_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/snippets/edit.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snippets/index.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:syntax) %></th>
      <th><%= model_class.human_attribute_name(:privacy_setting) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= link_to snippet.title, snippet_path(snippet), class: "btn btn-xs btn-success" %></td>
        <td><%= snippet.syntax %></td>
        <td><%= snippet.privacy_setting.titleize %></td>
        <td><%= link_to snippet.user.name, user_snippets_path(snippet.user), class: "btn btn-xs btn-primary" %></td>
        <td><%=l snippet.created_at %></td>
        <td><%=l snippet.updated_at %></td>
        <td>
          <% if can?(:read, snippet) %>
            <%= link_to 'Clone',
                        snippet_clone_path(snippet), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can?(:manage, snippet) %>
            <%= link_to 'Edit',
                        edit_snippet_path(snippet), :class => 'btn btn-default btn-xs' %>
            <%= link_to 'Delete',
                        snippet_path(snippet),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/snippets/new.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snippets/show.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @snippet.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd class="code">
    <pre>
      <code class="<%= @snippet.syntax %>"><%= @snippet.code.gsub("\n", '') %></code>
    </pre>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:syntax) %>:</strong></dt>
  <dd><%= @snippet.syntax %></dd>
  <dt><strong><%= model_class.human_attribute_name(:privacy_setting) %>:</strong></dt>
  <dd><%= @snippet.privacy_setting.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @snippet.user.name %></dd>
  <dt><strong>Snippet's URL:</strong></dt>
  <dd><%= link_to snippet_url(@snippet) %></dd>
</dl>
  <%= link_to 'Back',
                snippets_path, :class => 'btn btn-default'  %>
  <%= link_to 'Clone',
                snippet_clone_path(@snippet), method: :post, :class => 'btn btn-default'  %>
<% if can? :manage, @snippet %>
  <%= link_to 'Edit',
                edit_snippet_path(@snippet), :class => 'btn btn-default' %>
  <%= link_to 'Delete',
                snippet_path(@snippet),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>